# Generated by Django 5.0.7 on 2024-07-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('instance', '0004_remove_instance_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='instance.instance'),
        ),
    ]
