# Generated by Django 5.0.7 on 2024-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_tag_contact_tags'),
        ('tags', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='tags.tag'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
