version: '3.8'

services:
  control:
    build: .
    command: >
      sh -c "mkdir -p /app/static /app/staticfiles && python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8888"
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    env_file:
      - .env
    networks:
      - minha_rede
    depends_on:
      - celery

  celery:
    build: .
    command: celery -A controler worker -l INFO -Q messages,webhook,default
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - minha_rede

networks:
  minha_rede:
    external: true