# Generated by Django 5.0.7 on 2024-07-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0003_rename_messages_upsert_instance_contacts_upsert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='is_active',
        ),
    ]
