# Generated by Django 5.0.7 on 2024-07-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0004_remove_instance_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='contacts_upsert',
        ),
    ]
