# Generated by Django 5.0.7 on 2024-08-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0005_remove_instance_contacts_upsert'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='public_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
