# Generated by Django 5.0.7 on 2024-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instance', '0006_instance_public_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='public_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
