# Generated by Django 5.0.7 on 2024-09-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instance', '0007_alter_instance_public_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_numbers', models.IntegerField()),
                ('sent_numbers', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('tracking_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('start_timeout', models.IntegerField()),
                ('end_timeout', models.IntegerField()),
                ('send_greeting', models.BooleanField(default=False)),
                ('id_progress', models.CharField(max_length=200)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='instance.instance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
