# Generated by Django 5.0.7 on 2024-09-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_enable_pause_campaign_end_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='total_numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
