# Generated by Django 4.2.4 on 2024-09-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_remove_campaign_instance_campaign_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='tracking_code',
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
