# Generated by Django 4.2.4 on 2024-09-24 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_remove_campaign_tracking_code_campaign_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='sent_numbers',
            new_name='send_erro',
        ),
        migrations.AddField(
            model_name='campaign',
            name='sent_success',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SendMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('erro', 'Erro')], max_length=10)),
                ('msg', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='campaign.campaign')),
            ],
        ),
    ]
