# Generated by Django 4.2.4 on 2024-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_rename_sent_numbers_campaign_send_erro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmensagem',
            name='code',
            field=models.CharField(default=200, max_length=10),
            preserve_default=False,
        ),
    ]
