# Generated by Django 4.2.4 on 2024-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_rename_sent_success_campaign_send_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
