# Generated by Django 4.2.4 on 2024-09-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_alter_campaign_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='end_time',
        ),
    ]
