# Generated by Django 4.2.4 on 2024-09-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0011_remove_campaign_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='responses',
            field=models.IntegerField(default=0),
        ),
    ]
